package com.maxfour.libreplayer.dagger.module

import android.content.Context
import com.maxfour.libreplayer.mvp.presenter.AlbumDetailsPresenter
import com.maxfour.libreplayer.mvp.presenter.AlbumDetailsPresenter.AlbumDetailsPresenterImpl
import com.maxfour.libreplayer.mvp.presenter.AlbumsPresenter
import com.maxfour.libreplayer.mvp.presenter.AlbumsPresenter.AlbumsPresenterImpl
import com.maxfour.libreplayer.mvp.presenter.ArtistDetailsPresenter
import com.maxfour.libreplayer.mvp.presenter.ArtistDetailsPresenter.ArtistDetailsPresenterImpl
import com.maxfour.libreplayer.mvp.presenter.ArtistsPresenter
import com.maxfour.libreplayer.mvp.presenter.ArtistsPresenter.ArtistsPresenterImpl
import com.maxfour.libreplayer.mvp.presenter.GenreDetailsPresenter
import com.maxfour.libreplayer.mvp.presenter.GenreDetailsPresenter.GenreDetailsPresenterImpl
import com.maxfour.libreplayer.mvp.presenter.GenresPresenter
import com.maxfour.libreplayer.mvp.presenter.GenresPresenter.GenresPresenterImpl
import com.maxfour.libreplayer.mvp.presenter.HomePresenter
import com.maxfour.libreplayer.mvp.presenter.HomePresenter.HomePresenterImpl
import com.maxfour.libreplayer.mvp.presenter.PlaylistSongsPresenter
import com.maxfour.libreplayer.mvp.presenter.PlaylistSongsPresenter.PlaylistSongsPresenterImpl
import com.maxfour.libreplayer.mvp.presenter.PlaylistsPresenter
import com.maxfour.libreplayer.mvp.presenter.PlaylistsPresenter.PlaylistsPresenterImpl
import com.maxfour.libreplayer.mvp.presenter.SearchPresenter
import com.maxfour.libreplayer.mvp.presenter.SearchPresenter.SearchPresenterImpl