package com.maxfour.libreplayer.fragments.mainactivity.home

import android.app.ActivityOptions
import android.content.res.ColorStateList
import android.os.Bundle
import android.util.DisplayMetrics
import android.view.*
import androidx.appcompat.widget.Toolbar
import androidx.recyclerview.widget.LinearLayoutManager
import com.bumptech.glide.Glide
import com.bumptech.glide.load.engine.DiskCacheStrategy
import com.maxfour.appthemehelper.common.ATHToolbarActivity
import com.maxfour.appthemehelper.util.ATHUtil
import com.maxfour.appthemehelper.util.ColorUtil
import com.maxfour.appthemehelper.util.ToolbarContentTintHelper
import com.maxfour.libreplayer.App
import com.maxfour.libreplayer.Constants
import com.maxfour.libreplayer.Constants.USER_BANNER
import com.maxfour.libreplayer.R
import com.maxfour.libreplayer.adapter.HomeAdapter
import com.maxfour.libreplayer.dialogs.OptionsSheetDialogFragment
import com.maxfour.libreplayer.extensions.show
import com.maxfour.libreplayer.fragments.base.AbsMainActivityFragment
import com.maxfour.libreplayer.helper.MusicPlayerRemote
import com.maxfour.libreplayer.interfaces.MainActivityFragmentCallbacks
import com.maxfour.libreplayer.loaders.SongLoader
import com.maxfour.libreplayer.model.Home
import com.maxfour.libreplayer.model.smartplaylist.HistoryPlaylist
import com.maxfour.libreplayer.model.smartplaylist.LastAddedPlaylist
import com.maxfour.libreplayer.model.smartplaylist.MyTopSongsPlaylist
import com.maxfour.libreplayer.mvp.presenter.HomePresenter
import com.maxfour.libreplayer.mvp.presenter.HomeView
import com.maxfour.libreplayer.util.NavigationUtil
import com.maxfour.libreplayer.util.PlayerColorUtil
import com.maxfour.libreplayer.util.PreferenceUtil
import kotlinx.android.synthetic.main.ab