package com.maxfour.libreplayer.activities.base

import android.animation.ValueAnimator
import android.graphics.Color
import android.os.Bundle
import android.view.View
import android.view.ViewGroup
import android.view.ViewTreeObserver
import androidx.annotation.LayoutRes
import androidx.fragment.app.Fragment
import com.google.android.material.bottomsheet.BottomSheetBehavior
import com.google.android.material.card.MaterialCardView
import com.maxfour.appthemehelper.util.ATHUtil
import com.maxfour.appthemehelper.util.ColorUtil
import com.maxfour.libreplayer.R
import com.maxfour.libreplayer.extensions.hide
import com.maxfour.libreplayer.extensions.show
import com.maxfour.libreplayer.fragments.MiniPlayerFragment
import com.maxfour.libreplayer.fragments.NowPlayingScreen
import com.maxfour.libreplayer.fragments.NowPlayingScreen.*
import com.maxfour.libreplayer.fragments.base.AbsPlayerFragment
import com.maxfour.libreplayer.fragments.player.adaptive.AdaptiveFragment
import com.maxfour.libreplayer.fragments.player.blur.BlurPlayerFragment
import com.maxfour.libreplayer.fragments.player.card.CardFragment
import com.maxfour.libreplayer.fragments.player.cardblur.CardBlurFragment
import com.maxfour.libreplayer.fragments.player.color.ColorFragment
import com.maxfour.libreplayer.fragments.player.fit.FitFragment
import com.maxfour.libreplayer.fragments.player.flat.FlatPlayerFragment
import com.maxfour.libreplayer.fragments.player.full.FullPlayerFragment
import com.maxfour.libreplayer.fragments.player.material.MaterialFragment
import com.maxfour.libreplayer.fragments.player.normal.PlayerFragment
import com.maxfour.libreplayer.fragments.player.peak.PeakPlayerFragment
import com.maxfour.libreplayer.fragments.player.plain.PlainPlayerFragment
import com.maxfour.libreplayer.fragments.player.simple.SimplePlayerFragment
import com.maxfour.libreplayer.fragments.player.tiny.TinyPlayerFragment
import com.maxfour.libreplayer.helper.MusicPlayerRemote
import com.maxfour.libreplayer.model.CategoryInfo
import com.maxfou